//
//  MainViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import UIKit
import AWSMobileHubHelper
import AWSCognitoIdentityProvider

class MainViewController: UIViewController {
    
    var pool: AWSCognitoIdentityUserPool?
    
    override func viewDidLoad() {
        if (AWSIdentityManager.default().isLoggedIn) {
            let storyboard = UIStoryboard(name: "MapView", bundle: nil)
            let viewController = storyboard.instantiateViewController(withIdentifier: "MapView")
            self.present(viewController, animated: true, completion: nil)
        }
        super.viewDidLoad()
        UINavigationBar.appearance().shadowImage = UIImage()
        UINavigationBar.appearance().setBackgroundImage(UIImage(), for: .default)
        self.pool = AWSCognitoIdentityUserPool.init(forKey: AWSCognitoUserPoolsSignInProviderKey)
    }
}
