//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//
//

import AWSCore
import AWSS3

// S3 Bucket Name
let S3BucketName = "vescle-userfiles-mobilehub-1713265082"

// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_MQc9RVwth"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "78tnbgtip46oja11rtic8qdv1p"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1lil7u5119g2u1ci5h35sciira7bgrd5upkju9ghomj095vvlq5b"

// Cognito Identity Pool ID
let AWSCognitoIdentityPoolId: String = "us-east-1:701ecd85-9e9c-4503-8057-5582c5cbf8ba"
