
//
//  UserIdentityViewController.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import MapKit
import AWSDynamoDB


//MARK: Global Declarations
let ann_arbor = CLLocation(latitude: 42.2808, longitude: -83.743);
//let my_house = bubble(name: "my house", lat: 42.271626, long: -83.738549)

class MapViewController: UIViewController {
    
    //MARK: Properties and Outlets
    let vescle = resizeImage(image: UIImage(named: "vescle")!,
                             targetSize: CGSize.init(width: 50, height: 50))
    
    @IBOutlet weak var mapView: MKMapView!
    
    let regionRadius: CLLocationDistance = 1000
    
    @IBOutlet weak var postButton: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let dynamoDBObjectMapper = AWSDynamoDBObjectMapper.default()
        
        if(manager.location != nil) {
            centerMapOnLocation(CLLocation(latitude: (manager.location?.coordinate.latitude)!, longitude: (manager.location?.coordinate.longitude)!))
        } else {
            centerMapOnLocation(ann_arbor)
        }
        
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 1000
        
        dynamoDBObjectMapper.scan(Vescles.self, expression: scanExpression) .continueWith(executor: AWSExecutor.mainThread(), block: { (task:AWSTask!) -> AnyObject! in
            if (task.error == nil) {
                if (task.result != nil) {
                    if let paginatedOutput = task.result {
                        for v in paginatedOutput.items as! [Vescles] {
                            if (Int64(v._expiration!)! >= getCurrentMillis()) {
                                let new_v = bubble(name: v._username!, lat: Double(v._latitude!)!, long: Double(v._longitude!)!, image: v._pictureS3!)
                                self.mapView.addAnnotation(new_v)
                            }
                        }
                    }
                }
            }
            else {
                print("Error: \(task.error)")
                
            }
            return nil
        })
        
        //mapView.addAnnotation(my_house)
        
        postButton?.layer.cornerRadius = 20
    }
    
    func centerMapOnLocation(_ location: CLLocation) {
        let coordinateRegion = MKCoordinateRegionMakeWithDistance(location.coordinate,
                                                                  regionRadius * 2.0, regionRadius * 2.0)
        mapView.setRegion(coordinateRegion, animated: true)
    }
    
    func mapView(_ mapView: MKMapView, viewForAnnotation annotation: MKAnnotation) -> MKAnnotationView? {
        if let annotation = annotation as? bubble{
            if let view = mapView.dequeueReusableAnnotationView(withIdentifier: annotation.identifier){
                return view
            }else{
                let view = MKAnnotationView(annotation: annotation, reuseIdentifier: annotation.identifier)
                view.image = vescle
                view.isEnabled = true
                view.canShowCallout = true
                
                let button = UIButton(type: .custom) as UIButton
                button.frame = CGRect(x: 20, y: 20, width: 20, height: 20)
                button.setBackgroundImage(#imageLiteral(resourceName: "Icon-20"), for: .normal)
                view.leftCalloutAccessoryView = button
                return view
            }
        }
        return nil
    }
    
    func mapView(_ mapView: MKMapView, annotationView view: MKAnnotationView, calloutAccessoryControlTapped control: UIControl) {
        
        if (control == view.leftCalloutAccessoryView) {
            self.performSegue(withIdentifier: "toVescle", sender: self)
        }
        
    }
}



func resizeImage(image: UIImage, targetSize: CGSize) -> UIImage {
    let size = image.size
    
    let widthRatio  = targetSize.width  / image.size.width
    let heightRatio = targetSize.height / image.size.height
    
    // Figure out what our orientation is, and use that to form the rectangle
    var newSize: CGSize
    if(widthRatio > heightRatio) {
        newSize = CGSize(width: size.width * heightRatio, height: size.height * heightRatio)
    } else {
        newSize = CGSize(width: size.width * widthRatio,  height: size.height * widthRatio)
    }
    
    // This is the rect that we've calculated out and this is what is actually used below
    let rect = CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height)
    
    // Actually do the resizing to the rect using the ImageContext stuff
    UIGraphicsBeginImageContextWithOptions(newSize, false, 1.0)
    image.draw(in: rect)
    let newImage = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    
    return newImage!
}


