//
//  Vescles.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Vescles: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var userId:String?
    var pictureS3:String?
    var text:String?
    var longitude:String?
    var latitude:String?
    var expiration:String?
    
    class func dynamoDBTableName() -> String {
        return "vescle-mobilehub-81544248-Vescles"
    }
    
    class func hashKeyAttribute() -> String {
        return "userId"
    }
    
    class func rangeKeyAttribute() -> String {
        return "pictureS3"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "userId" : "userId",
        ]
    }
}
